"""Updated data_models

Revision ID: 0e90496d14d9
Revises: 210bd4cafcd9
Create Date: 2025-05-06 16:01:38.855029

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e90496d14d9"
down_revision: Union[str, None] = "210bd4cafcd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("consumer_application_id", sa.UUID(), nullable=True),
        sa.Column("consumer_name", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("provider_application_id", sa.UUID(), nullable=True),
        sa.Column("provider_name", sa.String(), nullable=False),
        sa.Column(
            "permissions",
            sa.Enum("Read", "Write", "Both", name="permissionenum"),
            nullable=False,
        ),
        sa.Column("api_key_owner", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_owner"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consumer_application_id"],
            ["application.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_application_id"],
            ["application.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_table(
        "log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_application_id", sa.UUID(), nullable=True),
        sa.Column("consumer_application_id", sa.UUID(), nullable=True),
        sa.Column("request_url", sa.String(), nullable=False),
        sa.Column("request_data", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("Success", "Failed", name="statusenum"), nullable=False
        ),
        sa.Column("response_data", sa.Text(), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("http_method", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["consumer_application_id"],
            ["application.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_application_id"],
            ["application.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provider",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("secret_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("api_keys")
    op.drop_table("providers")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("secret_hash", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="providers_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("consumer_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("consumer_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("api_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "provider_application_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column("provider_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "permissions",
            postgresql.ENUM("read", "write", "both", name="permission"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("api_key_owner", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_application_id"],
            ["providers.id"],
            name="api_keys_provider_application_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="api_keys_pkey"),
        sa.UniqueConstraint("api_key", name="api_keys_api_key_key"),
    )
    op.drop_table("provider")
    op.drop_table("log")
    op.drop_table("api_key")
    op.drop_table("user")
    op.drop_table("application")
    # ### end Alembic commands ###
