"""Change foreign key constraint from provider_id to application_id in APIkey table

Revision ID: 4f7235ef721b
Revises: 6bdee9e11316
Create Date: 2025-05-07 04:06:43.427586

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f7235ef721b"
down_revision: Union[str, None] = "6bdee9e11316"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "api_key_consumer_application_id_fkey", "api_key", type_="foreignkey"
    )
    op.drop_constraint(
        "api_key_provider_application_id_fkey", "api_key", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "api_key", "application", ["provider_application_id"], ["id"]
    )
    op.create_foreign_key(
        None, "api_key", "application", ["consumer_application_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_key", type_="foreignkey")
    op.drop_constraint(None, "api_key", type_="foreignkey")
    op.create_foreign_key(
        "api_key_provider_application_id_fkey",
        "api_key",
        "provider",
        ["provider_application_id"],
        ["id"],
    )
    op.create_foreign_key(
        "api_key_consumer_application_id_fkey",
        "api_key",
        "provider",
        ["consumer_application_id"],
        ["id"],
    )
    # ### end Alembic commands ###
