"""Added api_key column

Revision ID: 53f0ad149906
Revises: 637e42c4b117
Create Date: 2025-05-12 02:24:07.096469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f0ad149906'
down_revision: Union[str, None] = '637e42c4b117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('api_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'api_keys', ['api_key'])
    op.drop_constraint('applications_user_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'])
    op.drop_constraint('logs_application_id_fkey', 'logs', type_='foreignkey')
    op.create_foreign_key(None, 'logs', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key('logs_application_id_fkey', 'logs', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_user_id_fkey', 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_column('api_keys', 'api_key')
    # ### end Alembic commands ###
