"""Added cascade delete for related tables

Revision ID: 637e42c4b117
Revises: bca487e3159e
Create Date: 2025-05-09 16:57:11.892645

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "637e42c4b117"
down_revision: Union[str, None] = "bca487e3159e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("applications_user_id_fkey", "applications", type_="foreignkey")
    op.create_foreign_key(
        None, "applications", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("logs_application_id_fkey", "logs", type_="foreignkey")
    op.create_foreign_key(
        None, "logs", "applications", ["application_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "logs", type_="foreignkey")
    op.create_foreign_key(
        "logs_application_id_fkey", "logs", "applications", ["application_id"], ["id"]
    )
    op.drop_constraint(None, "applications", type_="foreignkey")
    op.create_foreign_key(
        "applications_user_id_fkey", "applications", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
