"""Modified Relationships

Revision ID: 6d0da7f9a8aa
Revises: 70a1f120a5bc
Create Date: 2025-06-05 16:58:20.755052

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d0da7f9a8aa"
down_revision: Union[str, None] = "70a1f120a5bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applications", sa.Column("owner_id", sa.UUID(), nullable=False))
    op.drop_constraint(
        op.f("applications_user_id_fkey"), "applications", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "applications", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("applications", "user_id")
    op.add_column("consumer", sa.Column("owner_id", sa.UUID(), nullable=False))
    op.drop_constraint(
        op.f("consumer_provider_id_fkey"), "consumer", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("consumer_consumer_id_fkey"), "consumer", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "consumer", "applications", ["consumer_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "consumer", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "consumer", "applications", ["provider_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "consumer", type_="foreignkey")
    op.drop_constraint(None, "consumer", type_="foreignkey")
    op.drop_constraint(None, "consumer", type_="foreignkey")
    op.create_foreign_key(
        op.f("consumer_consumer_id_fkey"),
        "consumer",
        "applications",
        ["consumer_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("consumer_provider_id_fkey"),
        "consumer",
        "applications",
        ["provider_id"],
        ["id"],
    )
    op.drop_column("consumer", "owner_id")
    op.add_column(
        "applications",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "applications", type_="foreignkey")
    op.create_foreign_key(
        op.f("applications_user_id_fkey"),
        "applications",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("applications", "owner_id")
    # ### end Alembic commands ###
