"""Updated data_models(Consumer table)

Revision ID: 70a1f120a5bc
Revises: b0d242f5b24f
Create Date: 2025-06-05 16:29:14.558103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70a1f120a5bc'
down_revision: Union[str, None] = 'b0d242f5b24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('admin', 'user', name='roleenum')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('applications', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('applications', sa.Column('updated_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'applications', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'applications', 'users', ['created_by'], ['id'])
    op.add_column('consumer', sa.Column('consumer_id', sa.UUID(), nullable=False))
    op.add_column('consumer', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('consumer', sa.Column('updated_by', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('consumer_api_key_owner_id_fkey'), 'consumer', type_='foreignkey')
    op.create_foreign_key(None, 'consumer', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'consumer', 'applications', ['consumer_id'], ['id'])
    op.create_foreign_key(None, 'consumer', 'users', ['created_by'], ['id'])
    op.drop_column('consumer', 'api_key_owner_id')
    op.drop_column('consumer', 'expires_at')
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', name='roleenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('consumer', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('consumer', sa.Column('api_key_owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'consumer', type_='foreignkey')
    op.drop_constraint(None, 'consumer', type_='foreignkey')
    op.drop_constraint(None, 'consumer', type_='foreignkey')
    op.create_foreign_key(op.f('consumer_api_key_owner_id_fkey'), 'consumer', 'users', ['api_key_owner_id'], ['id'])
    op.drop_column('consumer', 'updated_by')
    op.drop_column('consumer', 'created_by')
    op.drop_column('consumer', 'consumer_id')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'updated_by')
    op.drop_column('applications', 'created_by')
    # ### end Alembic commands ###
