"""Initial migration

Revision ID: 78a9e107f468
Revises:
Create Date: 2025-05-06 19:35:58.606850

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78a9e107f468"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "provider",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("secret_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("consumer_application_id", sa.UUID(), nullable=True),
        sa.Column("consumer_name", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("provider_application_id", sa.UUID(), nullable=True),
        sa.Column("provider_name", sa.String(), nullable=False),
        sa.Column(
            "permissions",
            sa.Enum("Read", "Write", "Both", name="permissionenum"),
            nullable=False,
        ),
        sa.Column("api_key_owner", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_owner"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consumer_application_id"],
            ["provider.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_application_id"],
            ["provider.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_table(
        "log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_application_id", sa.UUID(), nullable=True),
        sa.Column("consumer_application_id", sa.UUID(), nullable=True),
        sa.Column("request_url", sa.String(), nullable=False),
        sa.Column("request_data", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("Success", "Failed", name="statusenum"), nullable=False
        ),
        sa.Column("response_data", sa.Text(), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("http_method", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["consumer_application_id"],
            ["provider.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_application_id"],
            ["provider.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("log")
    op.drop_table("api_key")
    op.drop_table("provider")
    op.drop_table("user")
    op.drop_table("application")

    # Drop Enums
    op.execute("DROP TYPE permissionenum")
    op.execute("DROP TYPE statusenum")
    # ### end Alembic commands ###
