"""Changing created_by and updated_by to nullable True

Revision ID: 7cb5bd8bf1c2
Revises: b5682bf7e1a8
Create Date: 2025-06-11 14:35:34.123396

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cb5bd8bf1c2"
down_revision: Union[str, None] = "b5682bf7e1a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("consumers", "created_by", existing_type=sa.UUID(), nullable=True)
    op.alter_column("consumers", "updated_by", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("consumers", "updated_by", existing_type=sa.UUID(), nullable=False)
    op.alter_column("consumers", "created_by", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
