"""changed application's secret_hash to Text datatype from string
 
Revision ID: 9670db387726
Revises: 53f0ad149906
Create Date: 2025-05-13 11:30:44.094541
 
"""
from typing import Sequence, Union
 
import sqlalchemy as sa
 
from alembic import op
 
# revision identifiers, used by Alembic.
revision: str = "9670db387726"
down_revision: Union[str, None] = "53f0ad149906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
 
 
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "applications",
        "secret_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.drop_constraint("applications_user_id_fkey", "applications", type_="foreignkey")
    op.create_foreign_key(
        None, "applications", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("logs_application_id_fkey", "logs", type_="foreignkey")
    op.create_foreign_key(
        None, "logs", "applications", ["application_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
 
 
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "logs", type_="foreignkey")
    op.create_foreign_key(
        "logs_application_id_fkey", "logs", "applications", ["application_id"], ["id"]
    )
    op.drop_constraint(None, "applications", type_="foreignkey")
    op.create_foreign_key(
        "applications_user_id_fkey", "applications", "users", ["user_id"], ["id"]
    )
    op.alter_column(
        "applications",
        "secret_hash",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###