"""Updated_data_models

Revision ID: b0d242f5b24f
Revises: b0eaf8c3d5a5
Create Date: 2025-06-04 15:02:46.308665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d242f5b24f'
down_revision: Union[str, None] = 'b0eaf8c3d5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'revoked', name='statusenum'), nullable=True),
    sa.Column('api_key_owner_id', sa.UUID(), nullable=False),
    sa.Column('permissions', sa.Enum('read', 'write', 'both', name='permissionenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('api_keys')
    op.create_unique_constraint(None, 'applications', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='unique')
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('consumer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'revoked', name='statusenum'), autoincrement=False, nullable=True),
    sa.Column('api_key_owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.ENUM('read', 'write', 'both', name='permissionenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_key_owner_id'], ['users.id'], name=op.f('api_keys_api_key_owner_id_fkey')),
    sa.ForeignKeyConstraint(['consumer_id'], ['applications.id'], name=op.f('api_keys_consumer_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['applications.id'], name=op.f('api_keys_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey')),
    sa.UniqueConstraint('api_key', name=op.f('api_keys_api_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('consumer')
    # ### end Alembic commands ###
