"""Changed application_id to nullable in log table

Revision ID: d74264aaa990
Revises: 9670db387726
Create Date: 2025-05-19 13:49:58.125485

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d74264aaa990"
down_revision: Union[str, None] = "9670db387726"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("logs", "application_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("logs", "application_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
